name: Deploy Hawk Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Stop Hawk Service
        env:
          HAWK_KEY: ${{ secrets.HAWK_KEY }}
        run: |
          echo "$HAWK_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no hawk@76.16.140.61 'sudo systemctl stop hawk'

      - name: Upload Hawk.jar
        env:
          HAWK_KEY: ${{ secrets.HAWK_KEY }}
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no target/hawk-0.0.1.jar hawk@76.16.140.61:/home/hawk/bot/hawk.jar

      - name: Start Hawk Service
        env:
          HAWK_KEY: ${{ secrets.HAWK_KEY }}
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no hawk@76.16.140.61 'sudo systemctl start hawk'
